spring:
  application:
    name: astra-aal-poc
  data:
    cassandra:
      keyspace-name: test_ks
      contact-points:
        - 127.0.0.1
      port: 9042
      local-datacenter: Cassandra
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

server.port: 8080
      
datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
  id: <db-id>
  region: us-east-1
  keyspace: test_ks
  application.token: <token>
  timeout: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


springfox:
  documentation:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      FlightController:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
