spring:
  application:
    name: astra-aal-poc
  data:
    cassandra:
      keyspace-name: <keyspace>
      username: <client_id>
      password: <secret>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

server.port: 8080
      
datastax.astra:
  secure-connect-bundle: secure-connect.zip
  session-metrics:
    - bytes-sent
    - bytes-received
    - connected-nodes
    - cql-requests
    - cql-client-timeouts
    - throttling.delay
    - throttling.queue-size
    - continuous-cql-requests
  node-metrics:
    - pool.open-connections
    - pool.in-flight
    - pool.available-streams
    - bytes-sent
    - bytes-received
    - cql-messages
    - errors.request.aborted
    - errors.request.read-timeouts
    - errors.request.write-timeouts
    - errors.request.unavailables
    - errors.request.others
    - retries.total
    - ignores.total
    - speculative-executions

astra.db:
  id: <db-id>
  region: us-east-1
  keyspace: <keyspace>
  application.token: <token>
  timeout: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


springfox:
  documentation:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      FlightController:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
