spring.application.name: astra-aal-poc

server.port: 8080

astra:
  dbid: <db-id>
  token: <token>
  timeout: 3

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  data:
    cassandra:
      keyspace-name: test_ks
      contact-points:
        - 127.0.0.1
      port: 9042
      local-datacenter: Cassandra

springfox:
  documentation:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      FlightController:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
